tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "planetscale/tap"
brew "direnv"
brew "git"
brew "go"
brew "jq"
brew "mas"
brew "mysql"
brew "mysql-client"
brew "peco"
brew "ruby-build"
brew "rbenv"
brew "tree"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "heroku/brew/heroku"
brew "planetscale/tap/pscale"
cask "alfred"
cask "docker"
cask "dotnet-sdk"
cask "dropbox"
cask "google-chrome"
cask "iterm2"
cask "postman"
cask "scroll-reverser"
cask "skitch"
cask "sourcetree"
cask "unity-hub"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Sequel Ace", id: 1518036000
mas "Slack", id: 803453959
